name: Deploy PR Previews
on:
  push:
    branches: [ git-preview ]
  pull_request:
    types:
        - opened
        - reopened
        - synchronize

  
jobs: 
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Set Domain
        run : echo "DOMAIN=${{ github.actor }}.github.io" >> $GITHUB_ENV
        
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci

      - name: Set Prodocution base URL for PR
        run: echo "BASE_URL=https://${{ env.DOMAIN }}/${{ github.event.repository.name }}/${{ env.PR_PATH }}/" >> $GITHUB_ENV

      - name: Build Astro Site
        run: npm run build

      - name: Deploy to PR Preview
        uses: peaceiris/actions-gh-pages@v3
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./public

      - name: Add Comment
        uses: hasura/comment-progress@v2.2.0
        with: 
           github-token: ${{ secrets.GITHUB_TOKEN }}
           repository: ${{ github.repository }}
           number: ${{ github.event.number }}
           id: deploy-preview
           message: "A preview of ${{ github.event.after }} is deplyed at:\n\n  ✨ ${{ env.BASE.URL }} ✨ "      