name: Deploy PR Previews
on:
  push:
    branches: [ github-deploy ]
    pull_request:
      types:
        - opened
        - reopened
        - synchronize

  
jobs: 
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy PR Preview 
        uses: rossjrw/pr-preview-action@v1.4.3
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          source-dir: .
          action: auto
          preview-branch: github-deploy