name: Deploy PR Previews
on:
  push:
    branches: [ gh-pages ]
  pull_request:
    types:
        - opened
        - reopened
        - synchronize

concurrency: preview-${{ github.ref }}
  
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Astro Site
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with: 
          name: preview-${{ github.sha }}
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: preview-${{ github.sha }}
          path: dist

      - name: Checkout Site Built
        uses: actions/checkout@v4
        with:
          path: gh-pages
          ref: gh-pages

      - name: Copy Build to Unique PR Folder
        run: |
          PR_FOLDER="pr-preview/pr-${{ github.event.pull_request.number }}"
          mkdir -p "${PR_FOLDER}"
          cp -r dist/* "${PR_FOLDER}/"

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Deploy PR Preview for PR #${{ github.event.pull_request.number }}"
          git push origin gh-preview
